export const ingredientsOptionsList = [
    { value: "5 spice powder;1002002", label: "5 Spice powder" },
    { value: "acorn squash;11482", label: "Acorn squash" },
    { value: "adobo sauce;6979", label: "Adobo sauce" },
    { value: "agave nectar;19912", label: "Agave nectar" },
    { value: "ahi tuna;15117", label: "Ahi tuna" },
    { value: "alfredo pasta sauce;93606", label: "Alfredo pasta sauce" },
    { value: "almond extract;1002050", label: "Almond extract" },
    { value: "almond flour;93740", label: "Almond flour" },
    { value: "almond milk;93607", label: "Almond milk" },
    { value: "almonds;12061", label: "Almonds" },
    { value: "amaretto;10014534", label: "Amaretto" },
    { value: "ancho chiles;10211962", label: "Ancho chiles" },
    { value: "anchovies;15001", label: "Anchovies" },
    { value: "andouille sausage;7064", label: "Andouille sausage" },
    { value: "angel food cake mix;18087", label: "Angel food cake mix" },
    { value: "angel hair pasta;10020420", label: "Angel hair pasta" },
    { value: "angostura bitters;93653", label: "Angostura bitters" },
    { value: "apple;9003", label: "Apple" },
    { value: "apple butter spread;19294", label: "Apple butter spread" },
    { value: "apple cider;1009016", label: "Apple cider" },
    { value: "apple juice;9016", label: "Apple juice" },
    { value: "apple pie spice;1042035", label: "Apple pie spice" },
    { value: "apricot preserves;19719", label: "Apricot preserves" },
    { value: "apricots;9021", label: "Apricots" },
    { value: "arborio rice;10020052", label: "Arborio rice" },
    { value: "arrowroot powder;20003", label: "Arrowroot powder" },
    {
        value: "artichoke heart quarters;93828",
        label: "Artichoke heart quarters",
    },
    { value: "artichokes;11007", label: "Artichokes" },
    { value: "arugula;11959", label: "Arugula" },
    { value: "asafoetida;1032035", label: "Asafoetida" },
    { value: "asafoetida powder;0", label: "Asafoetida powder" },
    { value: "asiago cheese;1001033", label: "Asiago cheese" },
    { value: "asian pear;9252", label: "Asian pear" },
    { value: "asparagus spears;11011", label: "Asparagus spears" },
    { value: "avocado;9037", label: "Avocado" },
    { value: "avocado oil;4581", label: "Avocado oil" },
    { value: "baby bell peppers;10311821", label: "Baby bell peppers" },
    { value: "baby bok choy;93636", label: "Baby bok choy" },
    { value: "baby carrots;11960", label: "Baby carrots" },
    { value: "baby corn;10011168", label: "Baby corn" },
    { value: "baby spinach leaves;11457", label: "Baby spinach leaves" },
    { value: "baby-back ribs;10010204", label: "Baby-back ribs" },
    { value: "baby-back ribs;10192", label: "Baby-back ribs" },
    { value: "bacon;10123", label: "Bacon" },
    { value: "bacon fat;4609", label: "Bacon fat" },
    { value: "baguette;18033", label: "Baguette" },
    { value: "baking bar;19078", label: "Baking bar" },
    { value: "baking powder;18371", label: "Baking powder" },
    { value: "baking soda;18372", label: "Baking soda" },
    { value: "balsamic glaze;98998", label: "Balsamic glaze" },
    { value: "balsamic vinegar;2069", label: "Balsamic vinegar" },
    { value: "bamboo shoots;11028", label: "Bamboo shoots" },
    { value: "banana;9040", label: "Banana" },
    { value: "basmati rice;10020444", label: "Basmati rice" },
    { value: "bay leaves;2004", label: "Bay leaves" },
    { value: "bbq sauce;6150", label: "Bbq sauce" },
    { value: "beans;16069", label: "Beans" },
    { value: "beef;23572", label: "Beef" },
    { value: "beef brisket;13023", label: "Beef brisket" },
    { value: "beef broth;6008", label: "Beef broth" },
    { value: "beef chuck roast;13786", label: "Beef chuck roast" },
    { value: "beef stock;6170", label: "Beef stock" },
    { value: "beef tenderloin;13926", label: "Beef tenderloin" },
    { value: "beer;14003", label: "Beer" },
    { value: "beer;14006", label: "Beer" },
    { value: "beets;11080", label: "Beets" },
    { value: "bell pepper;10211821", label: "Bell pepper" },
    { value: "berries;1009054", label: "Berries" },
    { value: "biscuit mix;18010", label: "Biscuit mix" },
    { value: "biscuits;18009", label: "Biscuits" },
    { value: "bittersweet chocolate;19903", label: "Bittersweet chocolate" },
    { value: "black bean sauce;99210", label: "Black bean sauce" },
    { value: "black beans;16015", label: "Black beans" },
    { value: "black olives;1059195", label: "Black olives" },
    { value: "black pepper;1002030", label: "Black pepper" },
    { value: "black sesame seeds;10012023", label: "Black sesame seeds" },
    { value: "blackberries;9042", label: "Blackberries" },
    { value: "blanched almonds;12062", label: "Blanched almonds" },
    { value: "blood orange;1009200", label: "Blood orange" },
    { value: "blue cheese;1004", label: "Blue cheese" },
    { value: "blueberries;9050", label: "Blueberries" },
    { value: "bok choy;11116", label: "Bok choy" },
    {
        value: "boneless skinless chicken breast;1055062",
        label: "Boneless skinless chicken breast",
    },
    { value: "bourbon;10014037", label: "Bourbon" },
    { value: "brandy;10114037", label: "Brandy" },
    { value: "bread;18064", label: "Bread" },
    { value: "bread flour;10120129", label: "Bread flour" },
    { value: "breakfast links;7919", label: "Breakfast links" },
    { value: "brie;1006", label: "Brie" },
    { value: "broccoli;11090", label: "Broccoli" },
    { value: "broccoli florets;10011090", label: "Broccoli florets" },
    { value: "brown rice;20040", label: "Brown rice" },
    { value: "brown rice flour;20090", label: "Brown rice flour" },
    { value: "brown sugar;19334", label: "Brown sugar" },
    { value: "brownie mix;18632", label: "Brownie mix" },
    { value: "brussel sprouts;11098", label: "Brussel sprouts" },
    { value: "bulgur;20012", label: "Bulgur" },
    { value: "butter;1001", label: "Butter" },
    { value: "butterhead lettuce;11250", label: "Butterhead lettuce" },
    { value: "buttermilk;1230", label: "Buttermilk" },
    { value: "butternut squash;11485", label: "Butternut squash" },
    { value: "butterscotch chips;19070", label: "Butterscotch chips" },
    { value: "cabbage;11109", label: "Cabbage" },
    { value: "caesar dressing;43015", label: "Caesar dressing" },
    { value: "cajun seasoning;1032028", label: "Cajun seasoning" },
    { value: "cake flour;10020129", label: "Cake flour" },
    { value: "candy canes;93759", label: "Candy canes" },
    { value: "candy coating;98857", label: "Candy coating" },
    { value: "candy melts;93775", label: "Candy melts" },
    { value: "canned black beans;16018", label: "Canned black beans" },
    { value: "canned diced tomatoes;11531", label: "Canned diced tomatoes" },
    { value: "canned garbanzo beans;16058", label: "Canned garbanzo beans" },
    { value: "canned green chiles;11980", label: "Canned green chiles" },
    { value: "canned kidney beans;16034", label: "Canned kidney beans" },
    { value: "canned mushrooms;11264", label: "Canned mushrooms" },
    { value: "canned pinto beans;16044", label: "Canned pinto beans" },
    {
        value: "canned red kidney beans;10016034",
        label: "Canned red kidney beans",
    },
    { value: "canned tomatoes;10011693", label: "Canned tomatoes" },
    { value: "canned tuna;10115121", label: "Canned tuna" },
    { value: "canned white beans;16051", label: "Canned white beans" },
    {
        value: "canned white cannellini beans;10016051",
        label: "Canned white cannellini beans",
    },
    { value: "cannellini beans;10716050", label: "Cannellini beans" },
    { value: "cantaloupe;9181", label: "Cantaloupe" },
    { value: "capers;2054", label: "Capers" },
    { value: "caramel sauce;19364", label: "Caramel sauce" },
    { value: "caramels;19074", label: "Caramels" },
    { value: "caraway seed;2005", label: "Caraway seed" },
    { value: "cardamom;2006", label: "Cardamom" },
    { value: "cardamom pods;1002006", label: "Cardamom pods" },
    { value: "carp;15008", label: "Carp" },
    { value: "carrots;11124", label: "Carrots" },
    { value: "cat fish filets;15010", label: "Cat fish filets" },
    { value: "cauliflower;11135", label: "Cauliflower" },
    { value: "cauliflower florets;10011135", label: "Cauliflower florets" },
    { value: "cauliflower rice;10111135", label: "Cauliflower rice" },
    { value: "celery;11143", label: "Celery" },
    { value: "celery ribs;10111143", label: "Celery ribs" },
    { value: "celery root;11141", label: "Celery root" },
    { value: "celery salt;1052047", label: "Celery salt" },
    { value: "celery seed;2007", label: "Celery seed" },
    { value: "cereal;8029", label: "Cereal" },
    { value: "champagne;10043155", label: "Champagne" },
    { value: "chana dal;99236", label: "Chana dal" },
    { value: "cheddar;1009", label: "Cheddar" },
    { value: "cheese;1041009", label: "Cheese" },
    { value: "cheese curds;98921", label: "Cheese curds" },
    { value: "cheese dip;1188", label: "Cheese dip" },
    { value: "cheese soup;6038", label: "Cheese soup" },
    { value: "cheese tortellini;10093727", label: "Cheese tortellini" },
    { value: "cherry;9070", label: "Cherry" },
    { value: "cherry pie filling;19314", label: "Cherry pie filling" },
    { value: "cherry tomatoes;10311529", label: "Cherry tomatoes" },
    { value: "chestnuts;12098", label: "Chestnuts" },
    { value: "chia seeds;12006", label: "Chia seeds" },
    { value: "chicken base;6080", label: "Chicken base" },
    { value: "chicken bouillon;6480", label: "Chicken bouillon" },
    {
        value: "chicken bouillon granules;1006080",
        label: "Chicken bouillon granules",
    },
    { value: "chicken breasts;5062", label: "Chicken breasts" },
    { value: "chicken broth;6194", label: "Chicken broth" },
    { value: "chicken drumsticks;5066", label: "Chicken drumsticks" },
    { value: "chicken legs;5075", label: "Chicken legs" },
    { value: "chicken pieces;1005006", label: "Chicken pieces" },
    { value: "chicken sausage;93668", label: "Chicken sausage" },
    { value: "chicken stock;6172", label: "Chicken stock" },
    { value: "chicken tenders;1015062", label: "Chicken tenders" },
    { value: "chicken thighs;5091", label: "Chicken thighs" },
    { value: "chicken wings;5100", label: "Chicken wings" },
    { value: "chickpea;16057", label: "Chickpea" },
    { value: "chile garlic sauce;93749", label: "Chile garlic sauce" },
    { value: "chili paste;6973", label: "Chili paste" },
    { value: "chili peppers;11962", label: "Chili peppers" },
    { value: "chili powder;2009", label: "Chili powder" },
    { value: "chili sauce;6972", label: "Chili sauce" },
    {
        value: "chipotle chiles in adobo;11632",
        label: "Chipotle chiles in adobo",
    },
    { value: "chipotle chilies;98839", label: "Chipotle chilies" },
    {
        value: "chipotle peppers in adobo;99223",
        label: "Chipotle peppers in adobo",
    },
    {
        value: "chive & onion cream cheese spread;93748",
        label: "Chive & onion cream cheese spread",
    },
    { value: "chocolate;19081", label: "Chocolate" },
    { value: "chocolate chip cookies;28027", label: "Chocolate chip cookies" },
    { value: "chocolate chunks;10419903", label: "Chocolate chunks" },
    { value: "chocolate ice cream;19270", label: "Chocolate ice cream" },
    { value: "chocolate milk;1102", label: "Chocolate milk" },
    {
        value: "chocolate sandwich cookies;18166",
        label: "Chocolate sandwich cookies",
    },
    { value: "chocolate syrup;14181", label: "Chocolate syrup" },
    {
        value: "chocolate wafer cookies;10118157",
        label: "Chocolate wafer cookies",
    },
    { value: "chorizo sausage;7019", label: "Chorizo sausage" },
    { value: "cider vinegar;2048", label: "Cider vinegar" },
    { value: "cilantro;11165", label: "Cilantro" },
    { value: "cinnamon roll;99020", label: "Cinnamon roll" },
    { value: "cinnamon stick;1002010", label: "Cinnamon stick" },
    { value: "cinnamon sugar;10219335", label: "Cinnamon sugar" },
    { value: "cinnamon swirl bread;18047", label: "Cinnamon swirl bread" },
    { value: "clam juice;14187", label: "Clam juice" },
    { value: "clams;15157", label: "Clams" },
    { value: "clarified butter;93632", label: "Clarified butter" },
    { value: "clove;1002011", label: "Clove" },
    { value: "coarse salt;1002047", label: "Coarse salt" },
    { value: "coarsely ground pepper;2035", label: "Coarsely ground pepper" },
    { value: "cocoa nibs;98846", label: "Cocoa nibs" },
    { value: "cocoa powder;19165", label: "Cocoa powder" },
    { value: "coconut;12104", label: "Coconut" },
    { value: "coconut aminos;98929", label: "Coconut aminos" },
    { value: "coconut butter;93746", label: "Coconut butter" },
    { value: "coconut cream;12115", label: "Coconut cream" },
    { value: "coconut extract;1032050", label: "Coconut extract" },
    { value: "coconut flour;93747", label: "Coconut flour" },
    { value: "coconut milk;12118", label: "Coconut milk" },
    { value: "coconut oil;4047", label: "Coconut oil" },
    { value: "coconut water;12119", label: "Coconut water" },
    { value: "cod;15015", label: "Cod" },
    { value: "coffee;14209", label: "Coffee" },
    { value: "cognac;10414037", label: "Cognac" },
    { value: "cola;14400", label: "Cola" },
    { value: "colby jack;1011", label: "Colby jack" },
    { value: "collard greens;11161", label: "Collard greens" },
    {
        value: "condensed cream of celery soup;6010",
        label: "Condensed cream of celery soup",
    },
    {
        value: "condensed cream of mushroom soup;6147",
        label: "Condensed cream of mushroom soup",
    },
    { value: "confectioner's swerve;99084", label: "Confectioner's swerve" },
    { value: "cooked bacon;10862", label: "Cooked bacon" },
    { value: "cooked brown rice;20041", label: "Cooked brown rice" },
    { value: "cooked chicken breast;5064", label: "Cooked chicken breast" },
    { value: "cooked ham;10802", label: "Cooked ham" },
    {
        value: "cooked long grain rice;10220445",
        label: "Cooked long grain rice",
    },
    { value: "cooked pasta;20421", label: "Cooked pasta" },
    { value: "cooked polenta;1008166", label: "Cooked polenta" },
    { value: "cooked quinoa;20137", label: "Cooked quinoa" },
    { value: "cooked wild rice;20088", label: "Cooked wild rice" },
    { value: "cookies;10118192", label: "Cookies" },
    { value: "coriander;2012", label: "Coriander" },
    { value: "corn;11168", label: "Corn" },
    { value: "corn bread mix;18022", label: "Corn bread mix" },
    { value: "corn chips;19003", label: "Corn chips" },
    { value: "corn flakes cereal;8020", label: "Corn flakes cereal" },
    { value: "corn flour;20019", label: "Corn flour" },
    { value: "corn kernels;11172", label: "Corn kernels" },
    { value: "corn oil;42289", label: "Corn oil" },
    { value: "corn tortillas;18363", label: "Corn tortillas" },
    { value: "cornbread;18023", label: "Cornbread" },
    { value: "corned beef;13346", label: "Corned beef" },
    { value: "cornish hens;5307", label: "Cornish hens" },
    { value: "cornmeal;35137", label: "Cornmeal" },
    { value: "cornstarch;20027", label: "Cornstarch" },
    { value: "cotija cheese;1001019", label: "Cotija cheese" },
    { value: "cottage cheese;1012", label: "Cottage cheese" },
    { value: "country bread;10018029", label: "Country bread" },
    { value: "courgettes;11477", label: "Courgettes" },
    { value: "couscous;20028", label: "Couscous" },
    { value: "cow pea;16063", label: "Cow pea" },
    { value: "crabmeat;10015136", label: "Crabmeat" },
    { value: "cracked pepper;2030", label: "Cracked pepper" },
    { value: "cranberries;9078", label: "Cranberries" },
    { value: "cranberry juice;43382", label: "Cranberry juice" },
    { value: "cream;1053", label: "Cream" },
    { value: "cream cheese;1017", label: "Cream cheese" },
    { value: "cream cheese block;1186", label: "Cream cheese block" },
    { value: "cream of chicken soup;6016", label: "Cream of chicken soup" },
    { value: "cream of tartar;18373", label: "Cream of tartar" },
    { value: "creamed corn;11174", label: "Creamed corn" },
    { value: "creamy peanut butter;10116098", label: "Creamy peanut butter" },
    { value: "creme fraiche;1001056", label: "Creme fraiche" },
    { value: "cremini mushrooms;11266", label: "Cremini mushrooms" },
    { value: "creole seasoning;1002031", label: "Creole seasoning" },
    { value: "crisp rice cereal;8066", label: "Crisp rice cereal" },
    { value: "croutons;18242", label: "Croutons" },
    { value: "crystallized ginger;93751", label: "Crystallized ginger" },
    { value: "cucumber;11206", label: "Cucumber" },
    { value: "cumin seeds;2014", label: "Cumin seeds" },
    { value: "cup cake;18139", label: "Cup cake" },
    { value: "currants;9085", label: "Currants" },
    { value: "curry leaves;93604", label: "Curry leaves" },
    { value: "dairy free milk;10016223", label: "Dairy free milk" },
    { value: "dark brown sugar;10019334", label: "Dark brown sugar" },
    { value: "dark chocolate;19904", label: "Dark chocolate" },
    {
        value: "dark chocolate candy bars;10019904",
        label: "Dark chocolate candy bars",
    },
    { value: "dark chocolate chips;10019071", label: "Dark chocolate chips" },
    { value: "dark sesame oil;1004058", label: "Dark sesame oil" },
    { value: "dates;9087", label: "Dates" },
    { value: "deep dish pie crust;18945", label: "Deep dish pie crust" },
    { value: "deli ham;10010151", label: "Deli ham" },
    { value: "deli turkey;7259", label: "Deli turkey" },
    { value: "dessert oats;8121", label: "Dessert oats" },
    { value: "dessert wine;10014057", label: "Dessert wine" },
    { value: "diced ham;99186", label: "Diced ham" },
    { value: "diet pop;14146", label: "Diet pop" },
    { value: "dijon mustard;1002046", label: "Dijon mustard" },
    { value: "dill;2045", label: "Dill" },
    { value: "dill pickles;10011937", label: "Dill pickles" },
    { value: "hot dog;21118", label: "Hot dog" },
    { value: "double cream;1011053", label: "Double cream" },
    { value: "dried apricots;9032", label: "Dried apricots" },
    { value: "dried basil;2003", label: "Dried basil" },
    { value: "dried cherries;93822", label: "Dried cherries" },
    { value: "dried chorizo;99233", label: "Dried chorizo" },
    { value: "dried cranberries;9079", label: "Dried cranberries" },
    { value: "dried dill;2017", label: "Dried dill" },
    { value: "dried onion;11284", label: "Dried onion" },
    {
        value: "dried porcini mushrooms;10011268",
        label: "Dried porcini mushrooms",
    },
    { value: "dried rubbed sage;1002038", label: "Dried rubbed sage" },
    { value: "dried thyme;2042", label: "Dried thyme" },
    { value: "dried tomatoes;11955", label: "Dried tomatoes" },
    { value: "dry bread crumbs;18079", label: "Dry bread crumbs" },
    { value: "dry milk;1090", label: "Dry milk" },
    { value: "dry mustard;1002024", label: "Dry mustard" },
    { value: "dry red wine;14097", label: "Dry red wine" },
    { value: "dry roasted peanuts;16090", label: "Dry roasted peanuts" },
    { value: "duck fat;4574", label: "Duck fat" },
    {
        value: "dutch process cocoa powder;10019165",
        label: "Dutch process cocoa powder",
    },
    { value: "edamame;11212", label: "Edamame" },
    { value: "egg substitute;1226", label: "Egg substitute" },
    { value: "egg vermicelli;20409", label: "Egg vermicelli" },
    { value: "egg whites;1124", label: "Egg whites" },
    { value: "egg yolk;1125", label: "Egg yolk" },
    { value: "eggnog;1057", label: "Eggnog" },
    { value: "eggplant;11209", label: "Eggplant" },
    { value: "elbow macaroni;10120499", label: "Elbow macaroni" },
    { value: "enchilada sauce;6599", label: "Enchilada sauce" },
    { value: "english cucumber;10111205", label: "English cucumber" },
    { value: "english muffin;18439", label: "English muffin" },
    { value: "erythritol;98887", label: "Erythritol" },
    { value: "escarole;11213", label: "Escarole" },
    { value: "espresso;14210", label: "Espresso" },
    { value: "evaporated milk;1214", label: "Evaporated milk" },
    { value: "extra firm tofu;16163", label: "Extra firm tofu" },
    {
        value: "extra virgin olive oil;1034053",
        label: "Extra virgin olive oil",
    },
    { value: "farfalle;10120420", label: "Farfalle" },
    { value: "farro;10020005", label: "Farro" },
    { value: "fat free mayo;42193", label: "Fat free mayo" },
    {
        value: "fat-free less-sodium chicken broth;6984",
        label: "Fat-free less-sodium chicken broth",
    },
    { value: "fennel;11957", label: "Fennel" },
    { value: "fennel seeds;2018", label: "Fennel seeds" },
    { value: "fenugreek leaf;98963", label: "Fenugreek leaf" },
    { value: "fenugreek seeds;2019", label: "Fenugreek seeds" },
    { value: "feta cheese;1019", label: "Feta cheese" },
    { value: "fettuccine;10020409", label: "Fettuccine" },
    { value: "fire roasted tomatoes;98849", label: "Fire roasted tomatoes" },
    { value: "fish;10115261", label: "Fish" },
    { value: "fish sauce;6179", label: "Fish sauce" },
    { value: "fish stock;6963", label: "Fish stock" },
    { value: "flank steak;23657", label: "Flank steak" },
    { value: "flax seeds;10012220", label: "Flax seeds" },
    { value: "fleur de sel;1022047", label: "Fleur de sel" },
    { value: "flour;20081", label: "Flour" },
    { value: "flour tortillas;10218364", label: "Flour tortillas" },
    { value: "fontina cheese;1020", label: "Fontina cheese" },
    { value: "food dye;10711111", label: "Food dye" },
    { value: "frank's redhot sauce;98878", label: "Frank's redhot sauce" },
    { value: "free range eggs;1123", label: "Free range eggs" },
    { value: "french bread;18029", label: "French bread" },
    { value: "fresh basil;2044", label: "Fresh basil" },
    { value: "fresh bean sprouts;11043", label: "Fresh bean sprouts" },
    { value: "fresh chives;11156", label: "Fresh chives" },
    { value: "fresh corn;11167", label: "Fresh corn" },
    { value: "fresh corn kernels;10011167", label: "Fresh corn kernels" },
    { value: "fresh figs;9089", label: "Fresh figs" },
    { value: "fresh fruit;9431", label: "Fresh fruit" },
    { value: "fresh herbs;10111297", label: "Fresh herbs" },
    { value: "fresh mint;2064", label: "Fresh mint" },
    { value: "fresh mozzarella;1026", label: "Fresh mozzarella" },
    { value: "fresh rosemary;2063", label: "Fresh rosemary" },
    { value: "fresh thyme leaves;2049", label: "Fresh thyme leaves" },
    { value: "fried onions;93709", label: "Fried onions" },
    { value: "frosting;19230", label: "Frosting" },
    { value: "froyo bars;93629", label: "Froyo bars" },
    { value: "frozen corn;11913", label: "Frozen corn" },
    { value: "frozen spinach;11463", label: "Frozen spinach" },
    { value: "fudge;19100", label: "Fudge" },
    { value: "fudge topping;10019348", label: "Fudge topping" },
    {
        value: "fun size almond joy bar;19065",
        label: "Fun size almond joy bar",
    },
    { value: "garam masala;93663", label: "Garam masala" },
    { value: "garbanzo bean flour;16157", label: "Garbanzo bean flour" },
    { value: "garlic;11215", label: "Garlic" },
    { value: "garlic paste;10111215", label: "Garlic paste" },
    { value: "garlic powder;1022020", label: "Garlic powder" },
    { value: "garlic powder;2020", label: "Garlic powder" },
    { value: "garlic salt;1062047", label: "Garlic salt" },
    { value: "gelatin;19177", label: "Gelatin" },
    { value: "gf chocolate cake mix;99040", label: "Gf chocolate cake mix" },
    { value: "gin;10514037", label: "Gin" },
    { value: "ginger;11216", label: "Ginger" },
    { value: "ginger ale;14136", label: "Ginger ale" },
    { value: "ginger paste;93754", label: "Ginger paste" },
    { value: "ginger-garlic paste;10093754", label: "Ginger-garlic paste" },
    { value: "gingersnap cookies;18172", label: "Gingersnap cookies" },
    { value: "gnocchi;98853", label: "Gnocchi" },
    { value: "goat cheese;1159", label: "Goat cheese" },
    { value: "golden raisins;9297", label: "Golden raisins" },
    { value: "gorgonzola;1011004", label: "Gorgonzola" },
    { value: "gouda cheese;1022", label: "Gouda cheese" },
    { value: "graham cracker crumbs;10018617", label: "Graham cracker crumbs" },
    {
        value: "graham cracker pie crust;18942",
        label: "Graham cracker pie crust",
    },
    { value: "graham crackers;18617", label: "Graham crackers" },
    { value: "grain blend;10020088", label: "Grain blend" },
    { value: "grand marnier;10314534", label: "Grand marnier" },
    { value: "granny smith apples;1089003", label: "Granny smith apples" },
    { value: "granola;8212", label: "Granola" },
    { value: "granulated garlic;1002020", label: "Granulated garlic" },
    { value: "grape tomatoes;10111529", label: "Grape tomatoes" },
    { value: "grapefruit;9112", label: "Grapefruit" },
    { value: "grapeseed oil;4517", label: "Grapeseed oil" },
    { value: "gravy;6997", label: "Gravy" },
    { value: "great northern beans;16025", label: "Great northern beans" },
    { value: "greek yogurt;1256", label: "Greek yogurt" },
    { value: "green beans;11052", label: "Green beans" },
    { value: "green bell pepper;11333", label: "Green bell pepper" },
    { value: "green chili pepper;31015", label: "Green chili pepper" },
    { value: "green food coloring;1441111", label: "Green food coloring" },
    { value: "green grapes;1019132", label: "Green grapes" },
    { value: "green olives;1029195", label: "Green olives" },
    { value: "green onions;11291", label: "Green onions" },
    { value: "greens;21052", label: "Greens" },
    { value: "grill cheese;10093624", label: "Grill cheese" },
    { value: "grill seasoning;1022034", label: "Grill seasoning" },
    { value: "ground allspice;2001", label: "Ground allspice" },
    { value: "ground ancho chili;1022009", label: "Ground ancho chili" },
    { value: "ground beef;10023572", label: "Ground beef" },
    { value: "ground chicken;5332", label: "Ground chicken" },
    {
        value: "ground chipotle chile pepper;1052009",
        label: "Ground chipotle chile pepper",
    },
    { value: "ground cinnamon;1012010", label: "Ground cinnamon" },
    { value: "ground cinnamon;2010", label: "Ground cinnamon" },
    { value: "ground cloves;2011", label: "Ground cloves" },
    {
        value: "ground coriander seeds;1002013",
        label: "Ground coriander seeds",
    },
    { value: "ground cumin;1002014", label: "Ground cumin" },
    { value: "ground flaxseed;12220", label: "Ground flaxseed" },
    { value: "ground ginger;2021", label: "Ground ginger" },
    { value: "ground lamb;17224", label: "Ground lamb" },
    { value: "ground mace;2022", label: "Ground mace" },
    { value: "ground nutmeg;2025", label: "Ground nutmeg" },
    { value: "ground pork;10219", label: "Ground pork" },
    { value: "ground pork sausage;7063", label: "Ground pork sausage" },
    { value: "ground veal;17142", label: "Ground veal" },
    { value: "gruyere;1023", label: "Gruyere" },
    { value: "guacamole;1009037", label: "Guacamole" },
    { value: "half n half;1049", label: "Half n half" },
    { value: "halibut fillet;15036", label: "Halibut fillet" },
    { value: "ham;10151", label: "Ham" },
    { value: "hamburger buns;18350", label: "Hamburger buns" },
    { value: "hard cooked eggs;1129", label: "Hard cooked eggs" },
    { value: "harissa;1006972", label: "Harissa" },
    { value: "hash brown potatoes;11390", label: "Hash brown potatoes" },
    { value: "hazelnuts;12120", label: "Hazelnuts" },
    {
        value: "healthy request cream of celery soup;6987",
        label: "Healthy request cream of celery soup",
    },
    { value: "hemp seeds;93602", label: "Hemp seeds" },
    { value: "herbes de provence;1012042", label: "Herbes de provence" },
    { value: "herbs;1002044", label: "Herbs" },
    {
        value: "hershey's kisses brand milk chocolates;93743",
        label: "Hershey's kisses brand milk chocolates",
    },
    { value: "hoisin sauce;6175", label: "Hoisin sauce" },
    { value: "honey mustard;99227", label: "Honey mustard" },
    { value: "horseradish;1002055", label: "Horseradish" },
    { value: "hot sauce;6168", label: "Hot sauce" },
    { value: "hummus;16158", label: "Hummus" },
    { value: "ice;10014412", label: "Ice" },
    { value: "ice cream;19095", label: "Ice cream" },
    {
        value: "instant chocolate pudding mix;19184",
        label: "Instant chocolate pudding mix",
    },
    { value: "instant coffee powder;14214", label: "Instant coffee powder" },
    {
        value: "instant espresso powder;10014214",
        label: "Instant espresso powder",
    },
    {
        value: "instant lemon pudding mix;19332",
        label: "Instant lemon pudding mix",
    },
    { value: "instant yeast;10118375", label: "Instant yeast" },
    { value: "irish cream;93764", label: "Irish cream" },
    { value: "italian bread;10028033", label: "Italian bread" },
    { value: "italian cheese blend;93651", label: "Italian cheese blend" },
    { value: "italian sausages;7036", label: "Italian sausages" },
    { value: "italian seasoning;1022027", label: "Italian seasoning" },
    { value: "jaggery;99002", label: "Jaggery" },
    { value: "jalapeno;11979", label: "Jalapeno" },
    { value: "jasmine rice;10120444", label: "Jasmine rice" },
    { value: "jelly;19297", label: "Jelly" },
    { value: "jicama;11603", label: "Jicama" },
    { value: "jimmies;93645", label: "Jimmies" },
    { value: "juice;1019016", label: "Juice" },
    { value: "jumbo shell pasta;10520420", label: "Jumbo shell pasta" },
    { value: "kaffir lime leaves;93633", label: "Kaffir lime leaves" },
    { value: "kahlua;93716", label: "Kahlua" },
    { value: "kalamata olives;1009195", label: "Kalamata olives" },
    { value: "kale;11233", label: "Kale" },
    { value: "ketchup;11935", label: "Ketchup" },
    { value: "kitchen bouquet;93768", label: "Kitchen bouquet" },
    { value: "kiwis;9148", label: "Kiwis" },
    { value: "kosher salt;1082047", label: "Kosher salt" },
    { value: "ladyfingers;18423", label: "Ladyfingers" },
    { value: "lamb;10017224", label: "Lamb" },
    { value: "lasagna noodles;10620420", label: "Lasagna noodles" },
    { value: "lb cake;18133", label: "Lb cake" },
    { value: "lean ground beef;23557", label: "Lean ground beef" },
    { value: "lean ground turkey;5662", label: "Lean ground turkey" },
    { value: "lean pork tenderloin;10060", label: "Lean pork tenderloin" },
    { value: "leeks;11246", label: "Leeks" },
    { value: "leg of lamb;17013", label: "Leg of lamb" },
    { value: "lemon;9150", label: "Lemon" },
    { value: "lemon curd;93834", label: "Lemon curd" },
    { value: "lemon extract;12311111", label: "Lemon extract" },
    { value: "lemon juice;9152", label: "Lemon juice" },
    { value: "lemon peel;9156", label: "Lemon peel" },
    { value: "lemon pepper;1012030", label: "Lemon pepper" },
    { value: "lemon wedges;1029150", label: "Lemon wedges" },
    { value: "lemongrass;11972", label: "Lemongrass" },
    { value: "lettuce;11252", label: "Lettuce" },
    { value: "lettuce leaves;93623", label: "Lettuce leaves" },
    { value: "light butter;4602", label: "Light butter" },
    { value: "light coconut milk;99009", label: "Light coconut milk" },
    { value: "light corn syrup;19350", label: "Light corn syrup" },
    { value: "light cream cheese;43274", label: "Light cream cheese" },
    { value: "light mayonnaise;4641", label: "Light mayonnaise" },
    { value: "light olive oil;1054053", label: "Light olive oil" },
    { value: "light soy sauce;10216124", label: "Light soy sauce" },
    { value: "lime;9159", label: "Lime" },
    { value: "lime juice;9160", label: "Lime juice" },
    { value: "lime wedges;1029159", label: "Lime wedges" },
    { value: "lime zest;1009159", label: "Lime zest" },
    { value: "linguine;10720420", label: "Linguine" },
    { value: "liquid smoke;93627", label: "Liquid smoke" },
    { value: "liquid stevia;10811111", label: "Liquid stevia" },
    { value: "liquor;14037", label: "Liquor" },
    { value: "live lobster;15147", label: "Live lobster" },
    { value: "long-grain rice;10220444", label: "Long-grain rice" },
    { value: "low fat buttermilk;1088", label: "Low fat buttermilk" },
    { value: "low fat milk;1082", label: "Low fat milk" },
    { value: "low fat milk;1174", label: "Low fat milk" },
    { value: "low fat plain yogurt;1117", label: "Low fat plain yogurt" },
    { value: "low fat ricotta cheese;1037", label: "Low fat ricotta cheese" },
    { value: "low fat sour cream;1179", label: "Low fat sour cream" },
    {
        value: "low sodium chicken broth;6970",
        label: "Low sodium chicken broth",
    },
    { value: "low sodium soy sauce;16424", label: "Low sodium soy sauce" },
    {
        value: "low-sodium chicken stock;1006970",
        label: "Low-sodium chicken stock",
    },
    {
        value: "lower sodium beef broth;10093741",
        label: "Lower sodium beef broth",
    },
    { value: "lump crab;10115136", label: "Lump crab" },
    { value: "m&m candies;19157", label: "M&m candies" },
    { value: "macadamia nuts;12131", label: "Macadamia nuts" },
    {
        value: "macaroni and cheese mix;32004",
        label: "Macaroni and cheese mix",
    },
    { value: "madras curry powder;2015", label: "Madras curry powder" },
    { value: "malt drink mix;14311", label: "Malt drink mix" },
    {
        value: "mandarin orange sections;9383",
        label: "Mandarin orange sections",
    },
    { value: "mandarin oranges;9218", label: "Mandarin oranges" },
    { value: "mango;9176", label: "Mango" },
    { value: "maple syrup;19911", label: "Maple syrup" },
    { value: "maraschino cherries;9328", label: "Maraschino cherries" },
    { value: "margarine;4073", label: "Margarine" },
    { value: "marinara sauce;10111549", label: "Marinara sauce" },
    { value: "marjoram;2023", label: "Marjoram" },
    { value: "marsala wine;14057", label: "Marsala wine" },
    { value: "marshmallow fluff;93644", label: "Marshmallow fluff" },
    { value: "marshmallows;19116", label: "Marshmallows" },
    { value: "masa harina;20317", label: "Masa harina" },
    { value: "mascarpone;93820", label: "Mascarpone" },
    { value: "mat beans;99144", label: "Mat beans" },
    { value: "matcha tea;98932", label: "Matcha tea" },
    { value: "mayonnaise;4025", label: "Mayonnaise" },
    { value: "meat;1015006", label: "Meat" },
    { value: "meat;1065062", label: "Meat" },
    { value: "meatballs;10110219", label: "Meatballs" },
    { value: "medjool dates;9421", label: "Medjool dates" },
    { value: "mexican cream;93772", label: "Mexican cream" },
    { value: "meyer lemon juice;1009152", label: "Meyer lemon juice" },
    { value: "milk;1077", label: "Milk" },
    { value: "milk chocolate chips;10019146", label: "Milk chocolate chips" },
    { value: "mint chutney;98991", label: "Mint chutney" },
    { value: "minute rice;20048", label: "Minute rice" },
    { value: "miracle whip;4014", label: "Miracle whip" },
    { value: "mirin;93830", label: "Mirin" },
    { value: "miso;16112", label: "Miso" },
    { value: "molasses;19304", label: "Molasses" },
    { value: "monterey jack cheese;1001025", label: "Monterey jack cheese" },
    { value: "mushroom;11260", label: "Mushroom" },
    { value: "mussels;15164", label: "Mussels" },
    { value: "mustard;2046", label: "Mustard" },
    { value: "mustard seeds;2024", label: "Mustard seeds" },
    { value: "napa cabbage;11119", label: "Napa cabbage" },
    { value: "navel oranges;9202", label: "Navel oranges" },
    { value: "nectarine;9191", label: "Nectarine" },
    { value: "new potatoes;11352", label: "New potatoes" },
    { value: "non-fat greek yogurt;1011256", label: "Non-fat greek yogurt" },
    { value: "nonfat cool whip;1200", label: "Nonfat cool whip" },
    { value: "nonfat milk;1085", label: "Nonfat milk" },
    { value: "nori;11446", label: "Nori" },
    { value: "nut butter;12195", label: "Nut butter" },
    { value: "nut meal;93620", label: "Nut meal" },
    { value: "nutella;19125", label: "Nutella" },
    { value: "nutritional yeast;93690", label: "Nutritional yeast" },
    { value: "oat flour;20132", label: "Oat flour" },
    { value: "oats;8120", label: "Oats" },
    { value: "oil;4582", label: "Oil" },
    {
        value: "oil packed sun dried tomatoes;11956",
        label: "Oil packed sun dried tomatoes",
    },
    { value: "okra;11278", label: "Okra" },
    { value: "old bay seasoning;1052034", label: "Old bay seasoning" },
    { value: "olive oil;4053", label: "Olive oil" },
    { value: "olives;9195", label: "Olives" },
    { value: "onion;11282", label: "Onion" },
    { value: "onion powder;2026", label: "Onion powder" },
    { value: "onion soup mix;6094", label: "Onion soup mix" },
    { value: "orange;9200", label: "Orange" },
    { value: "orange bell pepper;10011821", label: "Orange bell pepper" },
    { value: "orange juice;9206", label: "Orange juice" },
    {
        value: "orange juice concentrate;9214",
        label: "Orange juice concentrate",
    },
    { value: "orange liqueur;10414534", label: "Orange liqueur" },
    { value: "orange marmalade;19303", label: "Orange marmalade" },
    { value: "orange oil;12511111", label: "Orange oil" },
    { value: "orange zest;9216", label: "Orange zest" },
    { value: "oregano;2027", label: "Oregano" },
    { value: "oreo cookies;10018166", label: "Oreo cookies" },
    { value: "orzo;10920420", label: "Orzo" },
    { value: "oyster sauce;6176", label: "Oyster sauce" },
    { value: "oysters;15167", label: "Oysters" },
    { value: "palm sugar;93831", label: "Palm sugar" },
    { value: "pancetta;10410123", label: "Pancetta" },
    { value: "paneer;98847", label: "Paneer" },
    { value: "panko;10018079", label: "Panko" },
    { value: "papaya;9226", label: "Papaya" },
    { value: "paprika;2028", label: "Paprika" },
    { value: "parmigiano reggiano;1033", label: "Parmigiano reggiano" },
    { value: "parsley;11297", label: "Parsley" },
    { value: "parsley flakes;2029", label: "Parsley flakes" },
    { value: "parsnip;11298", label: "Parsnip" },
    {
        value: "part-skim mozzarella cheese;1028",
        label: "Part-skim mozzarella cheese",
    },
    { value: "pasta;20420", label: "Pasta" },
    { value: "pasta salad mix;99036", label: "Pasta salad mix" },
    { value: "pasta sauce;10011549", label: "Pasta sauce" },
    { value: "pastry flour;10020080", label: "Pastry flour" },
    { value: "peach;9236", label: "Peach" },
    { value: "peanut butter;16098", label: "Peanut butter" },
    { value: "peanut butter chips;93762", label: "Peanut butter chips" },
    { value: "peanut butter cups;19150", label: "Peanut butter cups" },
    { value: "peanut oil;4042", label: "Peanut oil" },
    { value: "peanuts;16091", label: "Peanuts" },
    { value: "pear liqueur;98988", label: "Pear liqueur" },
    { value: "pearl barley;20005", label: "Pearl barley" },
    { value: "pearl onions;10111282", label: "Pearl onions" },
    { value: "peas;11304", label: "Peas" },
    { value: "pecan;12142", label: "Pecan" },
    { value: "pecan pieces;10012142", label: "Pecan pieces" },
    { value: "pecorino;1038", label: "Pecorino" },
    { value: "penne;11120420", label: "Penne" },
    { value: "peperoncino;11976", label: "Peperoncino" },
    { value: "pepper jack cheese;1025", label: "Pepper jack cheese" },
    { value: "peppercorns;1022030", label: "Peppercorns" },
    {
        value: "peppermint baking chips;98858",
        label: "Peppermint baking chips",
    },
    { value: "peppermint extract;1022050", label: "Peppermint extract" },
    { value: "pepperoni;7057", label: "Pepperoni" },
    { value: "peppers;10111333", label: "Peppers" },
    { value: "pesto;93698", label: "Pesto" },
    { value: "pickle relish;11944", label: "Pickle relish" },
    { value: "pickles;11937", label: "Pickles" },
    { value: "pico de gallo;27027", label: "Pico de gallo" },
    { value: "pie crust;18334", label: "Pie crust" },
    {
        value: "pimento stuffed olives;1049195",
        label: "Pimento stuffed olives",
    },
    { value: "pimientos;11943", label: "Pimientos" },
    { value: "pine nuts;12147", label: "Pine nuts" },
    { value: "pineapple;9266", label: "Pineapple" },
    { value: "pineapple chunks;1029354", label: "Pineapple chunks" },
    { value: "pineapple in juice;9354", label: "Pineapple in juice" },
    { value: "pineapple juice;9273", label: "Pineapple juice" },
    { value: "pink himalayan salt;1032047", label: "Pink himalayan salt" },
    { value: "pinto beans;16043", label: "Pinto beans" },
    { value: "pistachios;12151", label: "Pistachios" },
    { value: "pita;18413", label: "Pita" },
    { value: "pizza crust;93770", label: "Pizza crust" },
    { value: "pizza mix;98924", label: "Pizza mix" },
    { value: "plain greek yogurt;1001256", label: "Plain greek yogurt" },
    { value: "plain nonfat yogurt;1118", label: "Plain nonfat yogurt" },
    { value: "plain yogurt;1001116", label: "Plain yogurt" },
    { value: "plantain;9277", label: "Plantain" },
    { value: "plum;9279", label: "Plum" },
    { value: "plum tomatoes;10411529", label: "Plum tomatoes" },
    { value: "poblano peppers;10011333", label: "Poblano peppers" },
    { value: "polenta;10035137", label: "Polenta" },
    { value: "polish sausage;7059", label: "Polish sausage" },
    { value: "pomegranate juice;9442", label: "Pomegranate juice" },
    { value: "pomegranate molasses;10042040", label: "Pomegranate molasses" },
    { value: "pomegranate seeds;9286", label: "Pomegranate seeds" },
    { value: "popcorn;19034", label: "Popcorn" },
    { value: "poppy seeds;2033", label: "Poppy seeds" },
    { value: "pork;10010219", label: "Pork" },
    { value: "Pork & Beans;16009", label: "Pork & Beans" },
    { value: "pork belly;10005", label: "Pork belly" },
    { value: "pork butt;10084", label: "Pork butt" },
    { value: "pork chops;10010062", label: "Pork chops" },
    { value: "pork links;1007063", label: "Pork links" },
    { value: "pork loin chops;10062", label: "Pork loin chops" },
    { value: "pork loin roast;10225", label: "Pork loin roast" },
    { value: "pork roast;10010225", label: "Pork roast" },
    { value: "pork shoulder;10072", label: "Pork shoulder" },
    { value: "pork tenderloin;10218", label: "Pork tenderloin" },
    { value: "port;10114057", label: "Port" },
    { value: "portabella mushrooms;11265", label: "Portabella mushrooms" },
    { value: "pot roast;23612", label: "Pot roast" },
    { value: "potato chips;19411", label: "Potato chips" },
    { value: "potato starch;11413", label: "Potato starch" },
    { value: "potatoes;11362", label: "Potatoes" },
    { value: "poultry seasoning;2034", label: "Poultry seasoning" },
    { value: "powdered sugar;19336", label: "Powdered sugar" },
    { value: "pretzel sandwiches;19047", label: "Pretzel sandwiches" },
    {
        value: "processed american cheese;1253",
        label: "Processed american cheese",
    },
    { value: "prosciutto;10010123", label: "Prosciutto" },
    { value: "provolone cheese;1035", label: "Provolone cheese" },
    { value: "prunes;9291", label: "Prunes" },
    { value: "puff pastry;18337", label: "Puff pastry" },
    { value: "pumpkin;11422", label: "Pumpkin" },
    { value: "pumpkin pie filling;11426", label: "Pumpkin pie filling" },
    { value: "pumpkin pie spice;1002035", label: "Pumpkin pie spice" },
    { value: "pumpkin puree;11424", label: "Pumpkin puree" },
    { value: "pumpkin seeds;12014", label: "Pumpkin seeds" },
    { value: "queso fresco;1228", label: "Queso fresco" },
    { value: "quick cooking oats;8402", label: "Quick cooking oats" },
    { value: "quinoa;20035", label: "Quinoa" },
    { value: "quinoa flour;93773", label: "Quinoa flour" },
    { value: "radicchio;11952", label: "Radicchio" },
    { value: "radishes;11429", label: "Radishes" },
    { value: "raisins;9299", label: "Raisins" },
    { value: "rajma masala;10193663", label: "Rajma masala" },
    { value: "ramen noodles;6583", label: "Ramen noodles" },
    { value: "ranch dressing;4639", label: "Ranch dressing" },
    { value: "ranch dressing mix;93733", label: "Ranch dressing mix" },
    { value: "raspberries;9302", label: "Raspberries" },
    { value: "raspberry jam;10719297", label: "Raspberry jam" },
    { value: "raw cashews;12087", label: "Raw cashews" },
    { value: "raw shrimp;15152", label: "Raw shrimp" },
    {
        value: "ready-to-serve Asian fried rice;93721",
        label: "Ready-to-serve Asian fried rice",
    },
    {
        value: "real bacon recipe pieces;99229",
        label: "Real bacon recipe pieces",
    },
    { value: "red apples;1079003", label: "Red apples" },
    { value: "red bell peppers;11821", label: "Red bell peppers" },
    { value: "red cabbage;11112", label: "Red cabbage" },
    { value: "red chilli;11819", label: "Red chilli" },
    { value: "red delicious apples;1059003", label: "Red delicious apples" },
    { value: "red food coloring;1451111", label: "Red food coloring" },
    { value: "red grapefruit juice;98926", label: "Red grapefruit juice" },
    { value: "red grapes;9132", label: "Red grapes" },
    { value: "red kidney beans;16033", label: "Red kidney beans" },
    { value: "red lentils;10016069", label: "Red lentils" },
    { value: "red onion;10011282", label: "Red onion" },
    { value: "red pepper flakes;1032009", label: "Red pepper flakes" },
    { value: "red pepper powder;2031", label: "Red pepper powder" },
    { value: "red potatoes;10011355", label: "Red potatoes" },
    { value: "red velvet cookie;18157", label: "Red velvet cookie" },
    { value: "red wine;14096", label: "Red wine" },
    { value: "red wine vinegar;1022068", label: "Red wine vinegar" },
    {
        value: "reduced fat shredded cheddar cheese;1001168",
        label: "Reduced fat shredded cheddar cheese",
    },
    { value: "refried beans;16202", label: "Refried beans" },
    {
        value: "refrigerated crescent rolls;93618",
        label: "Refrigerated crescent rolls",
    },
    {
        value: "refrigerated pizza dough;93610",
        label: "Refrigerated pizza dough",
    },
    {
        value: "refrigerated sugar cookie dough;18205",
        label: "Refrigerated sugar cookie dough",
    },
    { value: "rhubarb;9307", label: "Rhubarb" },
    { value: "rib tips;98937", label: "Rib tips" },
    { value: "rice;20444", label: "Rice" },
    { value: "rice flour;20061", label: "Rice flour" },
    { value: "rice krispies cereal;8065", label: "Rice krispies cereal" },
    { value: "rice milk;93761", label: "Rice milk" },
    { value: "rice noodles;20133", label: "Rice noodles" },
    { value: "rice paper;10118368", label: "Rice paper" },
    { value: "rice syrup;93784", label: "Rice syrup" },
    { value: "rice vinegar;1022053", label: "Rice vinegar" },
    { value: "rice wine;43479", label: "Rice wine" },
    { value: "ricotta salata;1036", label: "Ricotta salata" },
    { value: "ritz crackers;18621", label: "Ritz crackers" },
    { value: "roast beef;93713", label: "Roast beef" },
    { value: "roasted chicken;5114", label: "Roasted chicken" },
    { value: "roasted nuts;12135", label: "Roasted nuts" },
    { value: "roasted peanuts;16092", label: "Roasted peanuts" },
    { value: "roasted red peppers;11916", label: "Roasted red peppers" },
    { value: "roma tomatoes;10211529", label: "Roma tomatoes" },
    { value: "romaine lettuce;10111251", label: "Romaine lettuce" },
    { value: "root vegetables;10011298", label: "Root vegetables" },
    { value: "rosemary;2036", label: "Rosemary" },
    { value: "rotini pasta;11320420", label: "Rotini pasta" },
    { value: "rotisserie chicken;5348", label: "Rotisserie chicken" },
    { value: "round steak;23617", label: "Round steak" },
    { value: "rub;1012034", label: "Rub" },
    { value: "rum extract;12211111", label: "Rum extract" },
    { value: "runny honey;19296", label: "Runny honey" },
    { value: "russet potatoes;11353", label: "Russet potatoes" },
    { value: "rutabaga;11435", label: "Rutabaga" },
    { value: "rye bread;18060", label: "Rye bread" },
    { value: "rye meal;98905", label: "Rye meal" },
    { value: "saffron threads;2037", label: "Saffron threads" },
    { value: "sage;2038", label: "Sage" },
    { value: "sage leaves;99226", label: "Sage leaves" },
    { value: "salad dressing;4114", label: "Salad dressing" },
    { value: "salami;7071", label: "Salami" },
    { value: "salmon fillet;15076", label: "Salmon fillet" },
    { value: "salsa;6164", label: "Salsa" },
    { value: "salsa verde;27028", label: "Salsa verde" },
    { value: "salt;2047", label: "Salt" },
    { value: "salt and pepper;1102047", label: "Salt and pepper" },
    { value: "salted butter;1001001", label: "Salted butter" },
    { value: "saltine crackers;18228", label: "Saltine crackers" },
    { value: "sandwich bun;18353", label: "Sandwich bun" },
    { value: "sauerkraut;11439", label: "Sauerkraut" },
    { value: "sausage;1017063", label: "Sausage" },
    { value: "sausage links;1037063", label: "Sausage links" },
    { value: "scotch bonnet chili;10011819", label: "Scotch bonnet chili" },
    { value: "sea salt;1012047", label: "Sea salt" },
    { value: "sea scallops;10015172", label: "Sea scallops" },
    { value: "seasoned bread crumbs;18376", label: "Seasoned bread crumbs" },
    { value: "seasoned rice vinegar;1032053", label: "Seasoned rice vinegar" },
    { value: "seasoned salt;1042047", label: "Seasoned salt" },
    { value: "seasoning;1042027", label: "Seasoning" },
    { value: "seasoning blend;1032027", label: "Seasoning blend" },
    { value: "seeds;93818", label: "Seeds" },
    { value: "self-rising flour;20129", label: "Self-rising flour" },
    {
        value: "semi sweet chocolate chips;10019903",
        label: "Semi sweet chocolate chips",
    },
    { value: "serrano chile;11977", label: "Serrano chile" },
    { value: "sesame oil;4058", label: "Sesame oil" },
    {
        value: "sesame seed hamburger buns;10018350",
        label: "Sesame seed hamburger buns",
    },
    { value: "sesame seeds;12023", label: "Sesame seeds" },
    { value: "shallot;11677", label: "Shallot" },
    { value: "sharp cheddar cheese;1031009", label: "Sharp cheddar cheese" },
    { value: "sheeps milk cheese;1011019", label: "Sheeps milk cheese" },
    { value: "shells;11020420", label: "Shells" },
    { value: "sherry;10114106", label: "Sherry" },
    { value: "sherry;10214106", label: "Sherry" },
    { value: "sherry vinegar;1012068", label: "Sherry vinegar" },
    { value: "shiitake mushroom caps;11238", label: "Shiitake mushroom caps" },
    { value: "short grain rice;10120052", label: "Short grain rice" },
    { value: "short pasta;20499", label: "Short pasta" },
    { value: "short ribs;10013149", label: "Short ribs" },
    { value: "shortbread cookies;18192", label: "Shortbread cookies" },
    { value: "shortcrust pastry;10018338", label: "Shortcrust pastry" },
    { value: "shortening;4615", label: "Shortening" },
    {
        value: "shredded cheddar cheese;1001009",
        label: "Shredded cheddar cheese",
    },
    { value: "shredded cheese;1011026", label: "Shredded cheese" },
    { value: "shredded chicken;1005114", label: "Shredded chicken" },
    { value: "shredded coconut;12108", label: "Shredded coconut" },
    {
        value: "shredded mexican cheese blend;1001251",
        label: "Shredded mexican cheese blend",
    },
    {
        value: "shredded mexican cheese blend;1251",
        label: "Shredded mexican cheese blend",
    },
    { value: "shredded mozzarella;1001026", label: "Shredded mozzarella" },
    { value: "silken tofu;16161", label: "Silken tofu" },
    { value: "sirloin steak;23625", label: "Sirloin steak" },
    { value: "skim milk ricotta;93630", label: "Skim milk ricotta" },
    {
        value: "skim vanilla greek yogurt;99033",
        label: "Skim vanilla greek yogurt",
    },
    {
        value: "skin-on bone-in chicken leg quarters;1005091",
        label: "Skin-on bone-in chicken leg quarters",
    },
    {
        value: "skinless boneless chicken breast halves;1045062",
        label: "Skinless boneless chicken breast halves",
    },
    {
        value: "skinless boneless chicken thighs;5096",
        label: "Skinless boneless chicken thighs",
    },
    { value: "skinned black gram;93718", label: "Skinned black gram" },
    { value: "slaw dressing;43016", label: "Slaw dressing" },
    { value: "slaw mix;10011109", label: "Slaw mix" },
    { value: "slivered almonds;10012061", label: "Slivered almonds" },
    { value: "smoked paprika;1012028", label: "Smoked paprika" },
    { value: "smoked salmon;15077", label: "Smoked salmon" },
    { value: "smoked sausage;7916", label: "Smoked sausage" },
    { value: "smooth peanut butter;16150", label: "Smooth peanut butter" },
    { value: "snapper fillets;15101", label: "Snapper fillets" },
    { value: "snow peas;11300", label: "Snow peas" },
    { value: "soda water;14121", label: "Soda water" },
    { value: "sour cream;1056", label: "Sour cream" },
    { value: "sourdough bowl;99169", label: "Sourdough bowl" },
    { value: "sourdough bread;10118029", label: "Sourdough bread" },
    { value: "soy milk;16223", label: "Soy milk" },
    { value: "soy protein powder;16122", label: "Soy protein powder" },
    { value: "soy sauce;16124", label: "Soy sauce" },
    { value: "spaghetti;11420420", label: "Spaghetti" },
    { value: "spaghetti squash;11492", label: "Spaghetti squash" },
    { value: "sparkling wine;43155", label: "Sparkling wine" },
    { value: "spelt flour;93823", label: "Spelt flour" },
    { value: "spicy brown mustard;1022046", label: "Spicy brown mustard" },
    { value: "spinach;10011457", label: "Spinach" },
    { value: "sprite;14144", label: "Sprite" },
    { value: "sprouts;11001", label: "Sprouts" },
    { value: "squash;10011485", label: "Squash" },
    { value: "sriracha sauce;1016168", label: "Sriracha sauce" },
    { value: "steaks;23232", label: "Steaks" },
    { value: "steel cut oats;93695", label: "Steel cut oats" },
    { value: "stevia;93628", label: "Stevia" },
    { value: "stew meat;10023618", label: "Stew meat" },
    { value: "stew vegetables;11583", label: "Stew vegetables" },
    { value: "stock;1006615", label: "Stock" },
    { value: "store-bought phyllo;18338", label: "Store-bought phyllo" },
    { value: "stout;93619", label: "Stout" },
    { value: "strawberries;9316", label: "Strawberries" },
    { value: "strawberry jam;10819297", label: "Strawberry jam" },
    { value: "strawberry jello;10219172", label: "Strawberry jello" },
    { value: "stuffing;18082", label: "Stuffing" },
    { value: "stuffing mix;18081", label: "Stuffing mix" },
    { value: "sub rolls;98940", label: "Sub rolls" },
    { value: "sugar;19335", label: "Sugar" },
    { value: "sugar snap peas;10011300", label: "Sugar snap peas" },
    { value: "sugar syrup;90480", label: "Sugar syrup" },
    { value: "sukrin sweetener;99190", label: "Sukrin sweetener" },
    { value: "summer savory;98961", label: "Summer savory" },
    { value: "summer squash;11641", label: "Summer squash" },
    { value: "sunflower oil;4584", label: "Sunflower oil" },
    { value: "sunflower seeds;12036", label: "Sunflower seeds" },
    { value: "sweet chilli sauce;98962", label: "Sweet chilli sauce" },
    { value: "sweet onion;11294", label: "Sweet onion" },
    { value: "sweet paprika;1002028", label: "Sweet paprika" },
    { value: "sweet pickle juice;93640", label: "Sweet pickle juice" },
    { value: "sweet pickle relish;11945", label: "Sweet pickle relish" },
    { value: "sweet potato;11507", label: "Sweet potato" },
    { value: "sweet tea;14355", label: "Sweet tea" },
    { value: "sweetened coconut;12109", label: "Sweetened coconut" },
    {
        value: "sweetened condensed milk;1095",
        label: "Sweetened condensed milk",
    },
    {
        value: "sweetened shredded coconut;12179",
        label: "Sweetened shredded coconut",
    },
    { value: "swiss chard;11147", label: "Swiss chard" },
    { value: "swiss cheese;1040", label: "Swiss cheese" },
    { value: "taco seasoning mix;2073", label: "Taco seasoning mix" },
    { value: "taco shells;18360", label: "Taco shells" },
    { value: "tahini;12698", label: "Tahini" },
    { value: "tamari;10116124", label: "Tamari" },
    { value: "tapioca flour;93696", label: "Tapioca flour" },
    { value: "tarragon;2041", label: "Tarragon" },
    { value: "tart apple;1029003", label: "Tart apple" },
    { value: "tea bags;10111111", label: "Tea bags" },
    { value: "tequila;10814037", label: "Tequila" },
    { value: "teriyaki sauce;6112", label: "Teriyaki sauce" },
    { value: "thai basil;1012044", label: "Thai basil" },
    { value: "thai chiles;11670", label: "Thai chiles" },
    { value: "thai red curry paste;93605", label: "Thai red curry paste" },
    { value: "thick-cut bacon;10310123", label: "Thick-cut bacon" },
    { value: "tilapia fillets;15261", label: "Tilapia fillets" },
    { value: "toast;18070", label: "Toast" },
    { value: "toffee bits;19383", label: "Toffee bits" },
    { value: "tofu;16213", label: "Tofu" },
    { value: "tomatillos;11954", label: "Tomatillos" },
    { value: "tomato juice;11886", label: "Tomato juice" },
    { value: "tomato paste;11887", label: "Tomato paste" },
    { value: "tomato puree;11547", label: "Tomato puree" },
    { value: "tomato sauce;11549", label: "Tomato sauce" },
    { value: "tomato soup;6159", label: "Tomato soup" },
    { value: "tomatoes;11529", label: "Tomatoes" },
    { value: "top blade steak;13523", label: "Top blade steak" },
    { value: "top round steak;23636", label: "Top round steak" },
    { value: "Top Sirloin;23584", label: "Top Sirloin" },
    { value: "tortilla;18364", label: "Tortilla" },
    { value: "tortilla chips;19056", label: "Tortilla chips" },
    { value: "triple sec;14534", label: "Triple sec" },
    { value: "truffle oil;1024053", label: "Truffle oil" },
    { value: "tuna;10015121", label: "Tuna" },
    { value: "turbinado sugar;19908", label: "Turbinado sugar" },
    { value: "turkey;5165", label: "Turkey" },
    { value: "turkey breast;5696", label: "Turkey breast" },
    { value: "turkey kielbasa;7955", label: "Turkey kielbasa" },
    { value: "turmeric;2043", label: "Turmeric" },
    { value: "turnips;11564", label: "Turnips" },
    { value: "unbleached flour;10020081", label: "Unbleached flour" },
    { value: "unsalted butter;1145", label: "Unsalted butter" },
    { value: "unsmoked back bacon;10130", label: "Unsmoked back bacon" },
    { value: "unsweetened applesauce;9019", label: "Unsweetened applesauce" },
    {
        value: "unsweetened coconut milk;12117",
        label: "Unsweetened coconut milk",
    },
    {
        value: "unsweetened shredded coconut;10012108",
        label: "Unsweetened shredded coconut",
    },
    { value: "vanilla bean;93622", label: "Vanilla bean" },
    { value: "vanilla bean paste;93813", label: "Vanilla bean paste" },
    { value: "vanilla essence;1012050", label: "Vanilla essence" },
    { value: "vanilla extract;2050", label: "Vanilla extract" },
    { value: "vanilla frosting;10019230", label: "Vanilla frosting" },
    {
        value: "vanilla instant pudding mix;19206",
        label: "Vanilla instant pudding mix",
    },
    { value: "vanilla protein powder;99076", label: "Vanilla protein powder" },
    { value: "vanilla wafers;18609", label: "Vanilla wafers" },
    { value: "vanilla yogurt;1119", label: "Vanilla yogurt" },
    { value: "vegan cheese;93701", label: "Vegan cheese" },
    { value: "vegan chocolate chips;98848", label: "Vegan chocolate chips" },
    { value: "vegan margarine;4673", label: "Vegan margarine" },
    { value: "vegetable broth;6615", label: "Vegetable broth" },
    { value: "vegetable oil;4513", label: "Vegetable oil" },
    { value: "vegetarian bacon;16542", label: "Vegetarian bacon" },
    { value: "vermouth;14132", label: "Vermouth" },
    { value: "vinaigrette;4135", label: "Vinaigrette" },
    { value: "vinegar;2053", label: "Vinegar" },
    { value: "vodka;14051", label: "Vodka" },
    { value: "walnuts;12155", label: "Walnuts" },
    { value: "water;14412", label: "Water" },
    { value: "water chestnuts;11590", label: "Water chestnuts" },
    { value: "water-packed tuna;15121", label: "Water-packed tuna" },
    { value: "watercress;11591", label: "Watercress" },
    { value: "watermelon chunks;9326", label: "Watermelon chunks" },
    { value: "wheat bran;20077", label: "Wheat bran" },
    { value: "wheat germ;20078", label: "Wheat germ" },
    { value: "whipped cream;1054", label: "Whipped cream" },
    { value: "whipped topping;42135", label: "Whipped topping" },
    { value: "whipping cream;1001053", label: "Whipping cream" },
    { value: "whiskey;14052", label: "Whiskey" },
    {
        value: "white balsamic vinegar;1012069",
        label: "White balsamic vinegar",
    },
    { value: "white bread;18069", label: "White bread" },
    { value: "white cake mix;18137", label: "White cake mix" },
    { value: "white cheddar;1011009", label: "White cheddar" },
    { value: "white chocolate;19087", label: "White chocolate" },
    { value: "white chocolate chips;10019087", label: "White chocolate chips" },
    { value: "white onion;10611282", label: "White onion" },
    { value: "white pepper;2032", label: "White pepper" },
    {
        value: "white whole wheat flour;93824",
        label: "White whole wheat flour",
    },
    { value: "white wine;14106", label: "White wine" },
    { value: "white wine vinegar;1002068", label: "White wine vinegar" },
    {
        value: "whole allspice berries;1002001",
        label: "Whole allspice berries",
    },
    { value: "whole chicken;5006", label: "Whole chicken" },
    { value: "whole coriander seeds;2013", label: "Whole coriander seeds" },
    { value: "whole cranberry sauce;9081", label: "Whole cranberry sauce" },
    { value: "whole kernel corn;11177", label: "Whole kernel corn" },
    { value: "whole star anise;1012002", label: "Whole star anise" },
    { value: "whole wheat bread;18075", label: "Whole wheat bread" },
    { value: "whole wheat flour;20080", label: "Whole wheat flour" },
    { value: "whole wheat tortillas;93675", label: "Whole wheat tortillas" },
    { value: "whole-grain mustard;1012046", label: "Whole-grain mustard" },
    { value: "wine;14084", label: "Wine" },
    { value: "wine vinegar;2068", label: "Wine vinegar" },
    { value: "winter squash;10111485", label: "Winter squash" },
    { value: "won ton wraps;10018368", label: "Won ton wraps" },
    { value: "worcestershire sauce;6971", label: "Worcestershire sauce" },
    { value: "wraps;10018364", label: "Wraps" },
    { value: "xanthan gum;93626", label: "Xanthan gum" },
    { value: "yeast;18375", label: "Yeast" },
    { value: "yellow bell pepper;11951", label: "Yellow bell pepper" },
    { value: "yellow cake mix;18144", label: "Yellow cake mix" },
    { value: "yellow onion;10511282", label: "Yellow onion" },
    { value: "yogurt;1116", label: "Yogurt" },
    { value: "yukon gold potato;10211362", label: "Yukon gold potato" },
];
